name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONTAIN_SKIP: ${{ !contains(github.event.head_commit.message, '#skip') }}

jobs:
  build_and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Test E2E
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3000
      - name: Test fail
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          severity: error
          details: Test Failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-20.04
    if: ${{ suscess() && github.event_name == 'push' && !env.CONTAIN_SKIP }} if
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Deployment success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ success() }}
        with:
          severity: info
          details: Deploy Seccueeded
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment fail
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          severity: error
          details: Deploy Failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment Cancelled
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ cancelled() }}
        with:
          severity: warn
          details: Deploy Cancelled
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !env.CONTAIN_SKIP }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
