name: URL Health Check

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

env:
  HEALTHZ_URL: https://badminton-web.onrender.com/api/healthz

jobs:
  url_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if URL is healthy
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.HEALTHZ_URL }}
          max-attempts: 3

      - name: Notify on failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          details: "URL Health Check Failed for ${{ env.HEALTHZ_URL }}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
